name = Turku Calendar - default
description = Default layout for Turku Calendar
preview = preview.png
template = turkucalendar-default-layout

; Regions
regions[emergency_messages] = Emergency messages
regions[branding]           = Branding
regions[navigation_top]     = Navigation top
regions[navigation]         = Navigation
regions[header_top]         = Header top
regions[header]             = Header
regions[highlighted]        = Highlighted
regions[help]               = Help
regions[tools_container]    = Tools container
regions[before_content]     = Before content
regions[content]            = Content
regions[sidebar_first]      = Sidebar first
regions[sidebar_second]     = Sidebar second
regions[after_content]      = After content
regions[before_footer]      = Before footer
regions[footer]             = Footer
regions[after_footer]       = After footer

; Stylesheets
stylesheets[all][] = dist/css/turkucalendar-default.layout.css
