<?php
/**
 * @file
 * Code for the Pori Attraction feature.
 */

include_once 'pori_attraction_feature.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function pori_attraction_feature_preprocess_node(&$vars) {
  global $language;
  if ($vars['type'] == 'attraction_card' && $vars['elements']['#view_mode'] == 'attraction_card_mosaic_item') {
    if (!empty($vars['field_product_liftup'][$language->language][0]['target_id'])) {
      $liftup = $vars['field_product_liftup'][$language->language][0]['target_id'];
    }
    if (!empty($vars['field_attraction_product_desc'][$language->language][0]['value'])) {
      $description = $vars['field_attraction_product_desc'][$language->language][0]['value'];
    }

    // If there is no product liftup or there's a liftup but no description, use the node title.
    if (empty($liftup) || (!empty($liftup) && empty($description))) {
      $vars['liftup_title'] = '<h2 class="attraction-card-mosaic__title">' . $vars['title'] . '</h2>';
    }

    // Try to find the product description.
    if (!empty($description)) {
      $vars['liftup_description'] = '<div class="attraction-card-mosaic__desc">' . truncate_utf8($description, 120, TRUE, TRUE, 90) . '</div>';
    }
    // And if that didn't work, use the lead paragraph.
    elseif (!empty($vars['field_lead_paragraph_et'][$language->language][0]['value'])) {
      $vars['liftup_description'] = '<div class="attraction-card-mosaic__ingress">' . truncate_utf8($vars['field_lead_paragraph_et'][$language->language][0]['value'], 100, TRUE, TRUE, 70) . '</div>';
    }
  }
}
