language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - composer self-update

  # Install Drush.
  - composer global require drush/drush:~8.1.5
  # DEBUG: Confirm Drush is installed.
  - drush version

  # Build the application.
  - ./build.sh new
