language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
  # Install Drush.
  - composer global require drush/drush:~8.1.5

  # Build the application.
  - ./build.sh new
