<?php
/**
 * @file
 * Code for the VisitPori override feature feature.
 */

include_once 'pori_visitpori_override_feature.features.inc';

/**
 * Implements hook_language_switch_links_alter().
 */
function pori_visitpori_override_feature_language_switch_links_alter(&$result, $type, $path) {
  $current_domain = domain_get_domain();
  $first_path_argument = arg(0);
  $excluded_domains = array(
    'en' => array(),
    'de' => array('pori_fi'),
    'sv' => array('pori_fi', 'visitpori_fi'),
  );

  if ($first_path_argument == 'node') {
    $current_node = node_load(arg(1));
    $node_type = $current_node->type;
    // Show all language selections in attraction cards.
    if ($node_type == 'attraction_card') {
      return;
    }
  }

  foreach ($excluded_domains as $lang => $domains) {
    if (in_array($current_domain['machine_name'], $domains)) {
      unset($result[$lang]);
    }
  }
}
