<?php
/**
 * @file
 * kada_search_sarnia_feature.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function kada_search_sarnia_feature_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-cMwsPXznsAZ7VDZZpoaIr9vsWZizbGQr'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cMwsPXznsAZ7VDZZpoaIr9vsWZizbGQr',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Target audience',
    'visibility' => 0,
  );

  $export['facetapi-0lEuNux6M1oXX3pdFry4zLKh063yqBpi'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0lEuNux6M1oXX3pdFry4zLKh063yqBpi',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Political party',
    'visibility' => 0,
  );

  $export['facetapi-1YHXhyAe9rKVCiO0P7ylsfaockMgfL6A'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1YHXhyAe9rKVCiO0P7ylsfaockMgfL6A',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Publish date',
    'visibility' => 0,
  );

  $export['facetapi-UpCC8TVrmAOs2e6sNmpTxPNZ5bzi1jH0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'UpCC8TVrmAOs2e6sNmpTxPNZ5bzi1jH0',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Trust unit',
    'visibility' => 0,
  );

  $export['facetapi-xQRvOUXBEEVXc3KpSNceDfMoo00PGDgZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'xQRvOUXBEEVXc3KpSNceDfMoo00PGDgZ',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Theme',
    'visibility' => 0,
  );

  $export['facetapi-4NAghk57O0P66Ye2hIHX2SJLyb6tQIGc'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '4NAghk57O0P66Ye2hIHX2SJLyb6tQIGc',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Keywords',
    'visibility' => 0,
  );

  $export['facetapi-t84YRB8UFR7abmT4tr9D99hD3xtR48d7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 't84YRB8UFR7abmT4tr9D99hD3xtR48d7',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Trustee role',
    'visibility' => 0,
  );

  $export['facetapi-asBdHYN0cOdtQdzq6gQpc927NjR9hsv9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'asBdHYN0cOdtQdzq6gQpc927NjR9hsv9',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Person type',
    'visibility' => 0,
  );

  $export['facetapi-cop7LpTV281IEUEE0NELoolZFPYyVt1z'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cop7LpTV281IEUEE0NELoolZFPYyVt1z',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Service classification',
    'visibility' => 0,
  );

  $export['facetapi-Z0IqJyWDd1CrBjjMlhK9eUjBEPiMjp12'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Z0IqJyWDd1CrBjjMlhK9eUjBEPiMjp12',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Office',
    'visibility' => 0,
  );

  $export['facetapi-2AmdxOeSX0L5N16qTKENjaTbN0ySOZuv'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '2AmdxOeSX0L5N16qTKENjaTbN0ySOZuv',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Content type',
    'visibility' => 0,
  );

  $export['facetapi-jLA0X0nAvfN2TSmyr5AbOSaJJAxgHBu7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jLA0X0nAvfN2TSmyr5AbOSaJJAxgHBu7',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'Audience',
    'visibility' => 0,
  );

  $export['facetapi-OuCL4ccSIk7lHpstP6zp1Vtxj1A1uEDX'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'OuCL4ccSIk7lHpstP6zp1Vtxj1A1uEDX',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
    ),
    'title' => 'District',
    'visibility' => 0,
  );

  return $export;
}
