name = Turku Calendar - front
description = Front page layout for Turku Calendar
preview = preview.png
template = turkucalendar-front-layout

; Regions
regions[emergency_messages] = Emergency messages
regions[branding]           = Branding
regions[navigation_top]     = Navigation top
regions[navigation]         = Navigation
regions[header_top]         = Header top
regions[header]             = Header
regions[top_carousel]       = Turkucalendar carousel
regions[top_tabs]           = Turkucalendar tabs
regions[highlighted]        = Highlighted
regions[help]               = Help
regions[tools_container]    = Tools container
regions[before_content]     = Before content
regions[content]            = Content
regions[after_content]      = After content
regions[before_footer]      = Before footer
regions[footer]             = Footer
regions[after_footer]       = After footer
regions[event_mosaic]       = Turkucalendar event mosaic
regions[event_list]         = Turkucalendar event list
regions[event_map]          = Turkucalendar event map
regions[filters]            = Turkucalendar event filters

; Stylesheets
stylesheets[all][] = css/layouts/turkucalendar-front/turkucalendar-front.layout.css
stylesheets[all][] = css/layouts/turkucalendar.css
