<?php
/**
 * @file
 * tkufi_search_feature.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function tkufi_search_feature_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-E7ldZFIeVv1Ub1Gc3juUsF7hagKOexgf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'E7ldZFIeVv1Ub1Gc3juUsF7hagKOexgf',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Time period',
    'visibility' => 0,
  );

  $export['facetapi-NFuoWDyjLrH3iqvpAe2Gxh9IC5a29BMe'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'NFuoWDyjLrH3iqvpAe2Gxh9IC5a29BMe',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Target audience',
    'visibility' => 0,
  );

  $export['facetapi-YpWMqpO9gq7H1NpTx0H1Yqy6G2Z32O5I'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'YpWMqpO9gq7H1NpTx0H1Yqy6G2Z32O5I',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Type',
    'visibility' => 0,
  );

  $export['facetapi-abt29sonAsIxpQBrbW7aKx02aBCOxPqd'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'abt29sonAsIxpQBrbW7aKx02aBCOxPqd',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Keywords',
    'visibility' => 0,
  );

  $export['facetapi-cKdQ4XFT2FzTf34NpEyRkyWkc9gp8qJt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cKdQ4XFT2FzTf34NpEyRkyWkc9gp8qJt',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Target audience',
    'visibility' => 0,
  );

  $export['facetapi-eLvyvqnLMiBQK8hAXcdQDrRgH1TMljGY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'eLvyvqnLMiBQK8hAXcdQDrRgH1TMljGY',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'District',
    'visibility' => 0,
  );

  $export['facetapi-woJfi9mKQxV3g6uMQEqItLf0N8VRIO0D'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'woJfi9mKQxV3g6uMQEqItLf0N8VRIO0D',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Service classification',
    'visibility' => 0,
  );

  $export['facetapi-xDkZCxPDTYLmiV9y1IUrb3Mk1xGU1jgr'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'xDkZCxPDTYLmiV9y1IUrb3Mk1xGU1jgr',
    'i18n_block_language' => array(),
    'i18n_mode' => 1,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'driveturku' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'driveturku',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Section',
    'visibility' => 0,
  );

  return $export;
}
