<?php

/**
 * @file
 * pori_news.features.features_overrides.inc
 */

/**
 * Implements hook_features_override_default_overrides().
 */
function pori_news_features_override_default_overrides() {
  // This code is only used for UI in features. Exported alters hooks do the magic.
  $overrides = array();

  // Exported overrides for: context

  // Exported overrides for: ds_field_settings

  // Exported overrides for: ds_layout_settings

  // Exported overrides for: field_group

  // Exported overrides for: field_instance

  // Exported overrides for: variable

 return $overrides;
}
