<?php

/**
 * Enable the overrides module.
 */
function pori_configuration_update_7100(&$sandbox) {
  module_enable(array('pori_configuration_overrides_feature'));
}

/**
 * Enable domain_views module.
 */
function pori_configuration_update_7101(&$sandbox) {
  module_enable(array('domain_views'));
}

/**
 * Enable contact information feature.
 */
function pori_configuration_update_7103(&$sandbox) {
  module_enable(array('pori_contact_information_feature'));
}
