<?php

/**
 * @file
 * Adds a Request URI condition to Context.
 */

/**
 * Implements hook_context_plugins().
 */
function kada_context_request_uri_condition_context_plugins() {
  $plugins['kada_context_request_uri_condition_context_condition_requesturi'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'kada_context_request_uri_condition'),
      'file' => 'kada_context_request_uri_condition.inc',
      'class' => 'kada_context_request_uri_condition_context_condition_requesturi',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function kada_context_request_uri_condition_context_registry() {
  return array(
    'conditions' => array(
      'requesturi' => array(
        'title' => t('Request URI'),
        'description' => t('Set this context based on the request URI.'),
        'plugin' => 'kada_context_request_uri_condition_context_condition_requesturi',
      ),
    ),
  );
}

/**
 * Implements hook_init().
 */
function kada_context_request_uri_condition_init() {
  if ($plugin = context_get_plugin('condition', 'requesturi')) {
    $plugin->execute();
  }
}
