<?php
/**
 * @file
 * Code for the KADA Blog feature.
 */

include_once 'kada_blog_feature.features.inc';

function kada_blog_feature_views_post_execute(&$view) {
  $kada_page_classes = &drupal_static('kada_page_classes');

  if ($view->name == 'kada_blog_image' && $view->current_display == 'blog_image') {
    if (!empty($view->result)) {
      $result = reset($view->result);

      foreach (array('field_field_main_image') as $field) {
        if (!empty($result->{$field})) {
          $kada_page_classes = 'has-main-image';
          break;
        }
      }
    }
  }
}
