<?php
define('VAR_RADIOACTIVITY_CHECKSUM_SALT', '');
define('VAR_RADIOACTIVITY_DRUPAL_ROOT', '/wwwroot/dev.turku.fi/current');
define('VAR_RADIOACTIVITY_TEMP_DIR', '/tmp');
define('VAR_RADIOACTIVITY_REDIS_HOST', 'memcache.local');
define('VAR_RADIOACTIVITY_REDIS_PORT', '6379');
define('VAR_RADIOACTIVITY_REDIS_PASSWORD', '');
define('PREDIS_BASE_PATH', VAR_RADIOACTIVITY_DRUPAL_ROOT . '/sites/all/libraries/predis/src/');
